# Generated by Django 5.0.7 on 2024-10-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_hub_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
